# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantreview',
            name='star1',
            field=models.CharField(default='fa-star-o text-secondary', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='star2',
            field=models.CharField(default='fa-star-o text-secondary', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='star3',
            field=models.CharField(default='fa-star-o text-secondary', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='star4',
            field=models.CharField(default='fa-star-o text-secondary', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='star5',
            field=models.CharField(default='fa-star-o text-secondary', max_length=50),
        ),
    ]
