# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-07 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20180701_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='min_service_charge',
            new_name='service_charge',
        ),
    ]
