# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-29 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20180707_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='min_order_tk',
            field=models.FloatField(default=150.0, verbose_name='Minimum Order'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='min_serve_time',
            field=models.IntegerField(default=30, verbose_name='Minimum Serve Time'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='service_charge',
            field=models.FloatField(default=30.0, verbose_name='Service Charge'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='vat_tax',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Vat/Tax'),
        ),
    ]
