# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.TextField(default=''),
        ),
    ]
