# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20180719_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
