# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantities',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
