# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
    ]
