# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180706_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
