# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180706_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discountID',
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='_type',
            field=models.CharField(choices=[('home', 'Home'), ('hestaurant', 'Restaurant')], default='home', max_length=100),
        ),
    ]
