# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180706_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='subtotal',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
