# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-07 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_order_expected_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
