# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20180702_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
