# Generated by Django 2.2.4 on 2019-08-02 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=160)),
                ('content', models.TextField()),
                ('food', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('service', models.IntegerField(default=0)),
                ('environment', models.IntegerField(default=0)),
                ('average', models.FloatField(default=0.0)),
                ('star1', models.CharField(default='fa-star', max_length=50)),
                ('star2', models.CharField(default='fa-star', max_length=50)),
                ('star3', models.CharField(default='fa-star', max_length=50)),
                ('star4', models.CharField(default='fa-star', max_length=50)),
                ('star5', models.CharField(default='fa-star', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
